-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-30 18:32:14 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
SPOOL oo_schema_output.txt

-- ================================================================
-- Cruise Booking System Database Design
--   student id: 34035958
--   student name: Chai Shou Zheng

-- Overview:
-- This database supports Ocean Odyssey (OO), a global travel company that books passengers 
-- on cruises operating worldwide. The system manages essential cruise operations, including:
--   • Recording operators and their ships (with details like ship code, name, tonnage, and capacity)
--   • Managing ship cabins by number, class, and sleeping capacity
--   • Scheduling cruises with unique IDs, names, ship assignments, and departure dates
--   • Storing passenger information including names, birthdate, gender, and guardian (if minor)
--   • Supporting diverse gender identities via a gender lookup table
--   • Handling shared household addresses and linking them to country records
--   • Booking passengers onto cruises and assigning cabins via a manifest
--   • Tracking each passenger’s first boarding time per cruise
--   • Mapping cruise itineraries through ports with clear arrival/departure sequencing
-- 
-- Real-world rules are built in using:
--   • CHECKs for valid cabin classes and itinerary flow (arrival or departure)
--   • Gender options managed through a lookup table
-- ================================================================

DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE ITINERARY CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER_GENDER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     address_id       NUMBER (6)  NOT NULL , 
     address_postcode VARCHAR2 (10)  NOT NULL , 
     address_town     VARCHAR2 (50)  NOT NULL , 
     address_street   VARCHAR2 (50)  NOT NULL , 
     country_code     CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.address_id IS 'Address ID (surrogate PK)' 
;

COMMENT ON COLUMN ADDRESS.address_postcode IS 'address postcode' 
;

COMMENT ON COLUMN ADDRESS.address_town IS 'address town' 
;

COMMENT ON COLUMN ADDRESS.address_street IS 'address street' 
;

COMMENT ON COLUMN ADDRESS.country_code IS 'country code' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( address_id ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_NK UNIQUE ( address_postcode , address_town , address_street , country_code ) ;

CREATE TABLE CABIN 
    ( 
     cabin_no                VARCHAR2 (5)  NOT NULL , 
     ship_code               VARCHAR2 (10)  NOT NULL , 
     cabin_sleeping_capacity NUMBER (3)  NOT NULL , 
     cabin_class             CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabinclass 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_no IS 'cabin number' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'ship code' 
;

COMMENT ON COLUMN CABIN.cabin_sleeping_capacity IS 'cabin sleeping capacity' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'cabin class,  I-Interior, O-Ocean View,  B-Balcony, S-Suite ' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_no, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code CHAR (3)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'country code' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'country name' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id              NUMBER (4)  NOT NULL , 
     cruise_name            VARCHAR2 (50)  NOT NULL , 
     cruise_description     VARCHAR2 (500)  NOT NULL , 
     cruise_depart_datetime DATE  NOT NULL , 
     cruise_cost_per_person NUMBER (8,2)  NOT NULL , 
     ship_code              VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'cruise name' 
;

COMMENT ON COLUMN CRUISE.cruise_description IS 'cruise description' 
;

COMMENT ON COLUMN CRUISE.cruise_depart_datetime IS 'cruise depart datetime' 
;

COMMENT ON COLUMN CRUISE.cruise_cost_per_person IS 'cruise cost per person' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'ship code' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE ITINERARY 
    ( 
     iti_datetime          DATE  NOT NULL , 
     cruise_id             NUMBER (4)  NOT NULL , 
     iti_arrival_departure CHAR (1)  NOT NULL , 
     port_code             CHAR (5)  NOT NULL 
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT chk_iti_arrival_departure 
    CHECK (iti_arrival_departure IN ('A', 'D')) 
;

COMMENT ON COLUMN ITINERARY.iti_datetime IS 'itinerary datetime' 
;

COMMENT ON COLUMN ITINERARY.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN ITINERARY.iti_arrival_departure IS 'itinerary arrival departure, A-Arrival, D-Departure' 
;

COMMENT ON COLUMN ITINERARY.port_code IS 'port code' 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_PK PRIMARY KEY ( iti_datetime, cruise_id ) ;

CREATE TABLE MANIFEST 
    ( 
     passenger_id                  NUMBER (8)  NOT NULL , 
     cruise_id                     NUMBER (4)  NOT NULL , 
     manifest_first_board_datetime DATE , 
     cabin_no                      VARCHAR2 (5)  NOT NULL , 
     ship_code                     VARCHAR2 (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN MANIFEST.passenger_id IS 'passenger id' 
;

COMMENT ON COLUMN MANIFEST.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN MANIFEST.manifest_first_board_datetime IS 'manifest first board datetime' 
;

COMMENT ON COLUMN MANIFEST.cabin_no IS 'cabin number' 
;

COMMENT ON COLUMN MANIFEST.ship_code IS 'ship code' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( passenger_id, cruise_id ) ;

CREATE TABLE OPERATOR 
    ( 
     operator_id        NUMBER (8)  NOT NULL , 
     operator_name      VARCHAR2 (50)  NOT NULL , 
     operator_ceo_fname VARCHAR2 (50) , 
     operator_ceo_lname VARCHAR2 (50) 
    ) 
;

COMMENT ON COLUMN OPERATOR.operator_id IS 'operator id' 
;

COMMENT ON COLUMN OPERATOR.operator_name IS 'operator name' 
;

COMMENT ON COLUMN OPERATOR.operator_ceo_fname IS 'operator ceo first name' 
;

COMMENT ON COLUMN OPERATOR.operator_ceo_lname IS 'operator ceo last name' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE PASSENGER 
    ( 
     passenger_id        NUMBER (8)  NOT NULL , 
     passenger_fname     VARCHAR2 (50) , 
     passenger_lname     VARCHAR2 (50) , 
     passenger_dob       DATE  NOT NULL , 
     passenger_phone_no  VARCHAR2 (15) , 
     passenger_gender_id VARCHAR2 (2)  NOT NULL , 
     guardian_id         NUMBER (8) , 
     address_id          NUMBER (6)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PASSENGER.passenger_id IS 'passenger id' 
;

COMMENT ON COLUMN PASSENGER.passenger_fname IS 'passenger first name' 
;

COMMENT ON COLUMN PASSENGER.passenger_lname IS 'passenger last name' 
;

COMMENT ON COLUMN PASSENGER.passenger_dob IS 'passenger date of birth' 
;

COMMENT ON COLUMN PASSENGER.passenger_phone_no IS 'passenger phone number' 
;

COMMENT ON COLUMN PASSENGER.passenger_gender_id IS 'Passenger gender id' 
;

COMMENT ON COLUMN PASSENGER.guardian_id IS 'passenger id' 
;

COMMENT ON COLUMN PASSENGER.address_id IS 'Address ID (surrogate PK)' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE PASSENGER_GENDER 
    ( 
     passenger_gender_id   VARCHAR2 (2)  NOT NULL , 
     passenger_gender_desc VARCHAR2 (30)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PASSENGER_GENDER.passenger_gender_id IS 'Passenger gender id' 
;

COMMENT ON COLUMN PASSENGER_GENDER.passenger_gender_desc IS 'Passenger gender description ' 
;

ALTER TABLE PASSENGER_GENDER 
    ADD CONSTRAINT PASSENGER_GENDER_PK PRIMARY KEY ( passenger_gender_id ) ;

CREATE TABLE PORT 
    ( 
     port_code      CHAR (5)  NOT NULL , 
     port_name      VARCHAR2 (50)  NOT NULL , 
     port_latitude  NUMBER (8,6)  NOT NULL , 
     port_longitude NUMBER (9,6)  NOT NULL , 
     country_code   CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'port code' 
;

COMMENT ON COLUMN PORT.port_name IS 'port name' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'port latitude' 
;

COMMENT ON COLUMN PORT.port_longitude IS 'port longitude' 
;

COMMENT ON COLUMN PORT.country_code IS 'country code' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code                   VARCHAR2 (10)  NOT NULL , 
     ship_name                   VARCHAR2 (50)  NOT NULL , 
     ship_commissioned_date      DATE  NOT NULL , 
     ship_tonnage                NUMBER (10,2)  NOT NULL , 
     ship_max_passenger_capacity NUMBER (5)  NOT NULL , 
     operator_id                 NUMBER (8)  NOT NULL , 
     country_code                CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'ship code' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'ship name' 
;

COMMENT ON COLUMN SHIP.ship_commissioned_date IS 'ship commissioned date' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'ship tonnage' 
;

COMMENT ON COLUMN SHIP.ship_max_passenger_capacity IS 'ship max passanger capacity' 
;

COMMENT ON COLUMN SHIP.operator_id IS 'operator id' 
;

COMMENT ON COLUMN SHIP.country_code IS 'country code' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT address_passenger_fk FOREIGN KEY 
    ( 
     address_id
    ) 
    REFERENCES ADDRESS 
    ( 
     address_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cabin_manifest_fk FOREIGN KEY 
    ( 
     cabin_no,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cabin_no,
     ship_code
    ) 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT country_address_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT country_ship_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT cruise_itenarary_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cruise_manifest_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT operator_ship_fk FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES OPERATOR 
    ( 
     operator_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT pass_gender_pass_fk FOREIGN KEY 
    ( 
     passenger_gender_id
    ) 
    REFERENCES PASSENGER_GENDER 
    ( 
     passenger_gender_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT pass_pass_fk FOREIGN KEY 
    ( 
     guardian_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT passenger_manifest_fk FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT port_itinerary_fk FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT ship_cruise_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off